#!/usr/bin/env python3
"""Translate index-en.html from Chinese to English"""

# Read the file
with open('/Users/weili/WorkBuddy/Claw/jobmatchai-deploy/index-en.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Translation dictionary (longer strings first)
translations = [
    ('JobMatchAI - 中丹求职助手', 'JobMatchAI - AI Job Search Assistant'),
    ('支持：中文 🇨🇳 | 英文 🇬🇧 | 丹麦语 🇩🇰', 'Supports: Chinese 🇨🇳 | English 🇬🇧 | Danish 🇩🇰'),
    ('lang="zh-CN"', 'lang="en"'),
    ('AI求职助手 - 智能简历分析、多语言翻译、职位匹配申请追踪', 'AI Job Assistant - Smart Resume Analysis, Multi-language Translation, Job Tracking'),
    ('求职,简历,AI,丹麦,瑞典,挪威', 'job search,resume,AI,Denmark,Sweden,Norway'),
    ('JobMatchAI - 智能求职助手', 'JobMatchAI - AI Job Search Assistant'),
    ('📄 AI智能简历助手', '📄 AI Resume Assistant'),
    ('🔒 当前会话已隔离', '🔒 Session Isolated'),
    ('（您的数据仅在本地处理，不会发送到服务器）', '(Your data is processed locally, never sent to servers)'),
    ('🚀 <span class="gradient-text">专业简历精修 + 精准求职信，让每次申请都更有竞争力</span>', '🚀 <span class="gradient-text">Professional Resume Polishing + Precision Cover Letters</span>'),
    ('第一步', 'Step 1'),
    ('第二步', 'Step 2'),
    ('第三步', 'Step 3'),
    ('上传简历', 'Upload Resume'),
    ('精修/翻译', 'Polish/Translate'),
    ('匹配分析', 'Match Analysis'),
    ('📄 立即开始：精修简历', '📄 Start Now: Polish Resume'),
    ('专业简历精修', 'Professional Resume Polishing'),
    ('在真实基础上优化表达，使简历更符合商务求职标准，提升专业形象', 'Optimize expression while keeping facts accurate, making your resume more professional'),
    ('求职申请参考', 'Job Application Reference'),
    ('多语言支持，基于简历与职位信息提供申请参考，助力求职准备', 'Multi-language support with application references based on your resume and target positions'),
    ('评估申请成功率', 'Application Success Rate'),
    ('智能分析简历与职位的匹配度，为您的申请策略提供参考建议', 'AI analyzes resume-job match rate and provides strategic application advice'),
    ('📄 精修简历', '📄 Polish Resume'),
    ('💼 意向职位', '💼 Target Position'),
    ('✉️ 求职申请', '✉️ Cover Letter'),
    ('⭐ 成为会员', '⭐ Membership'),
    ('💼 提供您的意向职位', '💼 Tell Us Your Target Position'),
    ('告诉我们您想申请的职位，我们将据此精修简历并生成定制求职申请', "Tell us the position you want to apply for, and we'll polish your resume and generate a customized cover letter"),
    ('📋 我们需要收集以下信息：', '📋 Information We Need:'),
    ('工作地点、要求等补充信息', 'Work location, requirements, and other supplementary info'),
    ('🔗 粘贴URL', '🔗 Paste URL'),
    ('📄 上传文档', '📄 Upload Doc'),
    ('✏️ 粘贴文本', '✏️ Paste Text'),
    ('粘贴招聘平台的职位链接：', 'Paste job posting URL from recruitment platform:'),
    ('💡 支持 LinkedIn、Jobindex、Indeed 等 · Siemens/Workday 等请用「粘贴文本」', '💡 Supports LinkedIn, Jobindex, Indeed · Use "Paste Text" for Siemens/Workday'),
    ('🔍 尝试抓取', '🔍 Try to Fetch'),
    ('上传职位描述文档：', 'Upload job description document:'),
    ('支持 PDF、DOCX、TXT 格式', 'Supports PDF, DOCX, TXT formats'),
    ('粘贴职位描述文本', 'Paste Job Description Text'),
    ('直接从招聘页面复制（Ctrl+A → Ctrl+C）粘贴即可', 'Copy from job posting (Ctrl+A → Ctrl+C) and paste here'),
    ('职位名称（可选）', 'Job Title (optional)'),
    ('公司名称（可选）', 'Company Name (optional)'),
    ('在此粘贴完整的职位描述文本（包括职责、要求等）...', 'Paste complete job description here (including responsibilities, requirements, etc.)...'),
    ('✅ 确认并使用此职位', '✅ Confirm & Use This Position'),
    ('📋 当前职位信息', '📋 Current Position Info'),
    ('职位名称', 'Job Title'),
    ('公司名称', 'Company Name'),
    ('职位描述...', 'Job Description...'),
    ('📄 精修简历', '📄 Polish Your Resume'),
    ('简历分析', 'Resume Analysis'),
    ('上传您的简历，AI将分析内容结构并提供优化建议', 'Upload your resume and AI will analyze its structure and provide optimization suggestions'),
    ('📄 点击或拖拽上传您的简历', '📄 Click or drag to upload your resume'),
    ('支持 PDF、Word、图片格式', 'Supports PDF, Word, Image formats'),
    ('或者粘贴简历内容', 'Or paste resume content'),
    ('粘贴简历文本', 'Paste Resume Text'),
    ('直接粘贴简历内容（支持从Word、网页等复制）', 'Paste resume content directly (supports copying from Word, web, etc.)'),
    ('开始分析', 'Start Analysis'),
    ('简历分析结果', 'Resume Analysis Results'),
    ('简历内容预览', 'Resume Content Preview'),
    ('简历结构评估', 'Resume Structure Evaluation'),
    ('简历长度', 'Resume Length'),
    ('识别语言', 'Detected Language'),
    ('内容完整度', 'Content Completeness'),
    ('预估字数', 'Estimated Word Count'),
    ('行', 'words'),
    ('内容概览', 'Content Overview'),
    ('关键信息', 'Key Information'),
    ('工作经历', 'Work Experience'),
    ('教育背景', 'Education'),
    ('技能特长', 'Skills'),
    ('精修简历', 'Polish Resume'),
    ('简历精修', 'Resume Polishing'),
    ('选择语言', 'Select Language'),
    ('目标语言', 'Target Language'),
    ('开始精修', 'Start Polishing'),
    ('精修中...', 'Polishing...'),
    ('精修结果', 'Polish Result'),
    ('下载精修简历', 'Download Polished Resume'),
    ('全部复制', 'Copy All'),
    ('复制成功', 'Copied!'),
    ('翻译简历', 'Translate Resume'),
    ('翻译中...', 'Translating...'),
    ('翻译结果', 'Translation Result'),
    ('✉️ 生成求职申请', '✉️ Generate Cover Letter'),
    ('求职申请', 'Cover Letter'),
    ('生成您的专属求职申请，突出您的核心优势并针对目标职位定制', 'Generate your personalized cover letter, highlighting your core strengths and tailored to the target position'),
    ('生成求职申请', 'Generate Cover Letter'),
    ('生成中...', 'Generating...'),
    ('申请内容预览', 'Cover Letter Preview'),
    ('复制全部内容', 'Copy All Content'),
    ('下载为Word', 'Download as Word'),
    ('一键复制', 'One-Click Copy'),
    ('会员特权', 'Member Benefits'),
    ('免费用户', 'Free Users'),
    ('Pro会员', 'Pro Members'),
    ('无限简历精修', 'Unlimited Resume Polishing'),
    ('有限额', 'Limited'),
    ('无限次', 'Unlimited'),
    ('多语言翻译', 'Multi-language Translation'),
    ('优先体验新功能', 'Early Access to New Features'),
    ('专属客服支持', 'Priority Support'),
    ('即将推出', 'Coming Soon'),
    ('🔍 全球职位搜索', '🔍 Global Job Search'),
    ('输入关键词，搜索多个国家的职位机会', 'Enter keywords to search job opportunities across multiple countries'),
    ('选择国家', 'Select Country'),
    ('全部', 'All'),
    ('德国', 'Germany'),
    ('瑞典', 'Sweden'),
    ('丹麦', 'Denmark'),
    ('英国', 'UK'),
    ('关键词', 'Keyword'),
    ('例如：ERP顾问、Dynamics AX、NetSuite', 'e.g., ERP Consultant, Dynamics AX, NetSuite'),
    ('搜索职位', 'Search Jobs'),
    ('搜索中...', 'Searching...'),
    ('搜索结果', 'Search Results'),
    ('共找到', 'Found'),
    ('个职位', 'jobs'),
    ('个职位（显示前', 'jobs (showing first'),
    ('个）', ')'),
    ('查看详情', 'View Details'),
    ('薪资', 'Salary'),
    ('未知', 'Unknown'),
    ('距离', 'Distance'),
    ('公司', 'Company'),
    ('地点', 'Location'),
    ('暂无职位', 'No jobs found'),
    ('请尝试不同的关键词或国家', 'Try different keywords or countries'),
    ('📋 申请追踪', '📋 Application Tracker'),
    ('记录您投递的职位，追踪申请状态', 'Track your job applications and monitor their status'),
    ('添加申请', 'Add Application'),
    ('申请日期', 'Application Date'),
    ('申请状态', 'Application Status'),
    ('已投递', 'Applied'),
    ('筛选中', 'Screening'),
    ('面试中', 'Interview'),
    ('已拿offer', 'Offer Received'),
    ('已拒绝', 'Rejected'),
    ('筛选状态：', 'Filter Status:'),
    ('暂无申请', 'No Applications'),
    ('开始记录您的第一个求职申请吧！', 'Start tracking your first job application!'),
    ('申请详情', 'Application Details'),
    ('备注', 'Notes'),
    ('面试时间', 'Interview Time'),
    ('加载中...', 'Loading...'),
    ('处理中...', 'Processing...'),
    ('请稍候...', 'Please wait...'),
    ('错误', 'Error'),
    ('成功', 'Success'),
    ('失败', 'Failed'),
    ('提示', 'Tip'),
    ('信息', 'Info'),
    ('注意', 'Note'),
    ('暂无数据', 'No Data'),
    ('完成', 'Done'),
    ('申请', 'Apply'),
    ('保存', 'Save'),
    ('取消', 'Cancel'),
    ('在此粘贴简历内容（可从Word、PDF等复制）', 'Paste resume content here (can copy from Word, PDF, etc.)'),
    ('在此粘贴简历内容', 'Paste resume content here'),
    ('开始分析简历', 'Start analyzing resume'),
    ('ERP顾问、销售经理等', 'ERP Consultant, Sales Manager, etc.'),
    ('例如：ERP顾问', 'e.g., ERP Consultant'),
    ('强烈推荐', 'Highly Recommended'),
    ('建议', 'Suggested'),
    ('可选', 'Optional'),
    ('接受', 'Accept'),
    ('拒绝', 'Reject'),
    ('全部接受', 'Accept All'),
    ('全部拒绝', 'Reject All'),
    ('接受并应用', 'Accept & Apply'),
    ('查看原文', 'View Original'),
    ('产品亮点', 'Product Features'),
    ('上传简历区域', 'Upload Area'),
    ('精修说明', 'Polish Options'),
    ('翻译说明', 'Translation Options'),
    ('生成说明', 'Generation Info'),
    ('搜索说明', 'Search Info'),
    ('申请追踪说明', 'Tracker Info'),
    ('简历结构建议', 'Resume Structure Suggestions'),
    ('内容优化建议', 'Content Optimization Suggestions'),
    ('职位名称（Job Title）', 'Job Title'),
    ('公司名称（Company Name）', 'Company Name'),
    ('职位描述（Job Description）— 可粘贴全文或上传文档', 'Job Description - Paste full text or upload document'),
    ('链接输入', 'URL Input'),
    ('文档上传', 'Document Upload'),
    ('抓取/上传结果', 'Fetch/Upload Result'),
    ('粘贴文本输入区', 'Text Input Area'),
    ('职位链接卡片（求职信用）', 'Job Link Card (for Cover Letter)'),
    ('简历内容', 'Resume Content'),
    ('AI 优化建议', 'AI Optimization Suggestions'),
    ('AI分析', 'AI Analysis'),
    ('优化建议', 'Optimization Suggestions'),
    ('结构完整', 'Structure Complete'),
    ('建议优化', 'Suggested Improvement'),
    ('缺失部分', 'Missing Sections'),
    ('优化方向', 'Optimization Direction'),
    ('简历完整度评估', 'Resume Completeness Assessment'),
    ('整体评价', 'Overall Assessment'),
    ('简历标题', 'Resume Title'),
    ('联系方式', 'Contact Info'),
    ('个人简介', 'Personal Summary'),
    ('项目经验', 'Project Experience'),
    ('技能证书', 'Skills & Certificates'),
    ('语言能力', 'Languages'),
    ('职位匹配度分析', 'Job Match Analysis'),
    ('匹配度', 'Match Rate'),
    ('高度匹配', 'High Match'),
    ('中度匹配', 'Medium Match'),
    ('低度匹配', 'Low Match'),
    ('匹配亮点', 'Matching Highlights'),
    ('待提升', 'Areas to Improve'),
    ('建议优化', 'Suggested Improvements'),
    ('添加跟进', 'Add Follow-up'),
    ('编辑', 'Edit'),
    ('删除', 'Delete'),
    ('重试', 'Retry'),
    ('关闭', 'Close'),
    ('确认', 'Confirm'),
]

# Apply translations
for cn, en in translations:
    if cn in content:
        content = content.replace(cn, en)
        print(f'✓ Translated: {cn[:30]}...')

# Write the file
with open('/Users/weili/WorkBuddy/Claw/jobmatchai-deploy/index-en.html', 'w', encoding='utf-8') as f:
    f.write(content)

print(f'\nDone! Applied {len(translations)} translations')
