#!/usr/bin/env python3
"""批量英文翻译脚本"""
import re

BASIC = [
    ("JobMatchAI - 智能求职助手", "JobMatchAI - Smart Job Assistant"),
    ("AI求职助手 - 智能简历分析、多语言翻译、职位匹配申请追踪", "AI Job Assistant - Smart Resume Analysis, Multilingual Translation & Application Tracking"),
    ("求职,简历,AI,丹麦,瑞典,挪威", "job,resume,AI,Denmark,Sweden,Norway"),
    ("🚀 专业简历精修 + 精准求职信", "🚀 Professional Resume Polish + Tailored Cover Letters"),
    ("让每次申请都更有竞争力", "Make every application more competitive"),
    ("📄 立即开始：精修简历", "📄 Get Started: Polish Your Resume"),
    ("💼 提供您的意向职位", "💼 Enter Your Target Position"),
    ("告诉我们您想申请的职位，我们将据此精修简历并生成定制求职申请", "Tell us the position you are applying for, and we will polish your resume and generate tailored applications"),
    ("📤 上传并精修简历", "📤 Upload & Polish Resume"),
    ("💡 支持 LinkedIn、Jobindex、Indeed 等 · Siemens/Workday 等请用「粘贴文本」", "💡 Supports LinkedIn, Jobindex, Indeed, etc. · For Siemens/Workday, use Paste Text"),
    ("智能简历精修：我们会将您的简历内容与意向职位描述进行匹配，在不过分夸大、不欺骗的前提下，调整表达方式使其更迎合职位要求，并优化格式使其符合商务求职标准。", "Smart Resume Polish: We match your resume content with the job description. Without exaggeration or deception, we adjust expressions to better fit the role and optimize formatting to professional standards."),
    ("请尽量在简历中提供完整的工作经历、培训、课程、参与的项目/活动等信息。", "Please provide complete work experience, training, courses, projects/activities etc. in your resume."),
    ("⚠️ 隐私提醒：", "⚠️ Privacy Notice:"),
    ("请勿在简历中放入您的个人敏感信息（如完整身份证号、银行卡号等）。您可在复制或下载简历后，再自行添加联系方式（电话、邮箱、LinkedIn）等信息。", "Do NOT include sensitive personal info (full ID, bank card numbers, etc.) in your resume. You can add contact info (phone, email, LinkedIn) after downloading."),
    ("✅ 简历上传成功！", "✅ Resume Uploaded!"),
    ("👇🏻 点击下方按钮开始分析", "👇🏻 Click the button below to analyze"),
    ("<strong style=\"color: #fff;\">隐私保护：</strong>您的简历仅在当前浏览器会话中使用，不会永久存储在我们的服务器上。", "<strong style=\"color: #fff;\">Privacy:</strong> Your resume is only used in the current browser session and will never be permanently stored on our servers."),
    ("如需保存，请下载到本地。所有AI处理在您的设备上完成。", "To save, download locally. All AI processing is done on your device."),
    ("或粘贴简历内容：", "Or paste resume content:"),
    ("将简历内容粘贴到这里...", "Paste your resume content here..."),
    ("✨ 专业分析简历", "✨ Analyze Resume"),
    ("📊 简历分析结果", "📊 Resume Analysis Results"),
    ("📄 精修后简历", "📄 Polished Resume"),
    ("✨ 改进建议", "✨ Improvement Suggestions"),
    ("工作经历", "Work Experience"),
    ("教育背景", "Education"),
    ("技能特长", "Skills"),
    ("语言能力", "Languages"),
    ("综合评分", "Overall Score"),
    ("工作年限", "Years of Experience"),
    ("匹配度", "Match Score"),
    ("复制全文", "Copy All"),
    ("下载 Word", "Download Word"),
    ("复制成功！", "Copied!"),
    ("暂无分析结果", "No analysis results yet"),
    ("请先上传或粘贴简历并点击分析", "Please upload or paste your resume and click Analyze"),
    ("正在分析简历，请稍候...", "Analyzing resume, please wait..."),
    ("精修简历", "Polish Resume"),
    ("开始分析", "Start Analysis"),
    ("分析简历", "Analyze Resume"),
    ("上传简历", "Upload Resume"),
    ("申请追踪", "Track Applications"),
    ("简历翻译", "Translate Resume"),
    ("搜索职位", "Search Jobs"),
    ("简历", "Resume"),
    ("求职信", "Cover Letter"),
    ("求职", "Job Search"),
    ("职位", "Position"),
    ("会员", "Premium"),
    ("订阅", "Subscribe"),
    ("注册", "Register"),
    ("登录", "Sign In"),
    ("邮箱", "Email"),
    ("密码", "Password"),
    ("公司", "Company"),
    ("公司名称", "Company Name"),
    ("公司名称（可选）", "Company Name (optional)"),
    ("技能", "Skills"),
    ("语言", "Languages"),
    ("搜索结果", "Search Results"),
    ("✉️ 生成定制求职信", "✉️ Generate Tailored Cover Letter"),
    ("在生成求职信之前，请先上传简历并分析：", "Please upload and analyze your resume first before generating a cover letter:"),
    ("请提供以下信息来生成求职信：", "Provide the following info to generate your cover letter:"),
    ("收件人（如 HR 部门、招聘经理等）", "Recipient (e.g., HR Department, Hiring Manager)"),
    ("收件人公司名称", "Recipient Company Name"),
    ("收件人姓名（可选）", "Recipient Name (optional)"),
    ("中文", "Chinese"),
    ("英文", "English"),
    ("丹麦文", "Danish"),
    ("德文", "German"),
    ("瑞典文", "Swedish"),
    ("挪威文", "Norwegian"),
    ("职位名称", "Job Title"),
    ("主要职责（可选）", "Main Responsibilities (optional)"),
    ("主要要求（可选）", "Key Requirements (optional)"),
    ("其他补充（可选）", "Additional Info (optional)"),
    ("✨ 生成求职信", "✨ Generate Cover Letter"),
    ("正在生成求职信...", "Generating cover letter..."),
    ("✉️ 求职信预览", "✉️ Cover Letter Preview"),
    ("复制求职信", "Copy Cover Letter"),
    ("下载求职信", "Download Cover Letter"),
    ("重新生成", "Regenerate"),
    ("调整语气", "Adjust Tone"),
    ("质量评分", "Quality Score"),
    ("尚未生成求职信", "No cover letter generated yet"),
    ("请先填写信息并点击生成", "Please fill in the info and click Generate above"),
    ("🔍 质量检测", "🔍 Quality Check"),
    ("检测求职信质量", "Check Cover Letter Quality"),
    ("正在进行质量检测...", "Running quality check..."),
    ("⭐ 成为会员", "⭐ Go Premium"),
    ("月度会员", "Monthly"),
    ("季度会员", "Quarterly"),
    ("半年度会员", "Semi-Annual"),
    ("年度会员", "Annual"),
    ("立即订阅", "Subscribe Now"),
    ("已订阅", "Subscribed"),
    ("免费用户", "Free User"),
    ("免费用户权限说明", "Free User Features"),
    ("已订阅高级功能", "Premium Features"),
    ("高级功能：", "Premium Features:"),
    ("无限次简历精修", "Unlimited Resume Polishing"),
    ("无限次求职信生成", "Unlimited Cover Letters"),
    ("简历 Word 导出", "Resume Word Export"),
    ("申请进度追踪", "Application Tracking"),
    ("无限保存职位", "Unlimited Job Saving"),
    ("专属客服支持", "Priority Support"),
    ("基础功能：", "Basic Features:"),
    ("每天 3 次简历精修", "3 Resume Polishes / Day"),
    ("每天 1 次求职信生成", "1 Cover Letter / Day"),
    ("基础简历分析", "Basic Resume Analysis"),
    ("语言翻译：", "Language Translation:"),
    ("简历翻译（英/丹/中）", "Resume Translation (EN/DK/CN)"),
    ("隐私政策", "Privacy Policy"),
    ("服务条款", "Terms of Service"),
    ("和", "and"),
    ("订阅成功！", "Subscription successful!"),
    ("订阅失败，请重试", "Subscription failed, please try again"),
    ("订阅已取消", "Subscription cancelled"),
    ("🌐 简历语种翻译", "🌐 Resume Translation"),
    ("简历翻译功能说明：", "Resume Translation Info:"),
    ("将您的简历内容翻译为目标语言，同时适配目标国家的职场表达习惯：", "Translate your resume to the target language, adapted to local workplace conventions:"),
    ("选择简历语言：", "Source Language:"),
    ("选择目标语言：", "Target Language:"),
    ("✨ 翻译简历", "✨ Translate Resume"),
    ("正在翻译...", "Translating..."),
    ("🔍 搜索职位", "🔍 Search Jobs"),
    ("关键词", "Keywords"),
    ("地点", "Location"),
    ("国家", "Country"),
    ("加载更多", "Load More"),
    ("正在搜索...", "Searching..."),
    ("未找到职位", "No jobs found"),
    ("职位详情", "Job Details"),
    ("申请", "Apply"),
    ("收藏", "Save"),
    ("已收藏", "Saved"),
    ("职位描述", "Job Description"),
    ("职位链接", "Job Link"),
    ("职位名称（可选）", "Job Title (optional)"),
    ("在此粘贴完整的职位描述文本（包括职责、要求等）...", "Paste the full job description here (including responsibilities, requirements, etc.)..."),
    ("📋 申请追踪", "📋 Application Tracker"),
    ("我的申请", "My Applications"),
    ("添加申请", "Add Application"),
    ("申请状态", "Status"),
    ("投递日期", "Applied Date"),
    ("跟进备注", "Notes"),
    ("待处理", "Pending"),
    ("已投递", "Applied"),
    ("已回复", "Replied"),
    ("已面试", "Interviewed"),
    ("已拒绝", "Rejected"),
    ("已录用", "Offer Received"),
    ("已完成", "Completed"),
    ("关于我们", "About Us"),
    ("联系邮箱", "Contact Email"),
    ("关闭", "Close"),
    ("取消", "Cancel"),
    ("确认", "Confirm"),
    ("保存", "Save"),
    ("删除", "Delete"),
    ("编辑", "Edit"),
    ("上传失败，请重试", "Upload failed, please try again"),
    ("生成失败，请重试", "Generation failed, please try again"),
    ("网络错误，请检查网络连接", "Network error, please check your connection"),
    ("请求超时，请重试", "Request timeout, please try again"),
    ("服务器错误，请稍后重试", "Server error, please try again later"),
    ("请先上传简历", "Please upload a resume first"),
    ("请先分析简历", "Please analyze your resume first"),
    ("请填写职位名称", "Please enter the job title"),
    ("请填写职位名称或粘贴职位描述", "Please enter a job title or paste a job description"),
    ("请先选择职位", "Please select a position first"),
    ("请先填写求职信信息", "Please fill in cover letter info first"),
    ("加载中...", "Loading..."),
    ("简历分析完成", "Resume analysis complete"),
    ("求职信生成完成", "Cover letter generation complete"),
    ("简历翻译完成", "Resume translation complete"),
    ("职位抓取完成", "Job fetch complete"),
    ("职位搜索完成", "Job search complete"),
    ("简历上传成功", "Resume uploaded successfully"),
    ("分析完成", "Analysis complete"),
    ("生成完成", "Generation complete"),
    ("翻译完成", "Translation complete"),
    ("正在加载", "Loading"),
    ("正在保存", "Saving"),
    ("正在删除", "Deleting"),
    ("正在发送", "Sending"),
    ("正在提交", "Submitting"),
    ("正在刷新", "Refreshing"),
    ("正在重试", "Retrying"),
    ("正在导出", "Exporting"),
    ("正在导入", "Importing"),
    ("正在复制", "Copying"),
    ("正在下载", "Downloading"),
    ("正在上传", "Uploading"),
    ("正在登录", "Signing in"),
    ("正在注册", "Registering"),
    ("正在登出", "Signing out"),
    ("正在订阅", "Subscribing"),
    ("正在取消订阅", "Unsubscribing"),
    ("正在验证", "Verifying"),
    ("正在初始化", "Initializing"),
    ("正在解析", "Parsing"),
    ("正在分析", "Analyzing"),
    ("正在生成", "Generating"),
    ("正在翻译", "Translating"),
    ("正在抓取", "Fetching"),
    ("正在搜索", "Searching"),
    ("正在匹配", "Matching"),
    ("正在优化", "Optimizing"),
    ("正在精修", "Polishing"),
    ("正在检测", "Checking"),
    ("简历内容不能为空", "Resume content cannot be empty"),
    ("职位描述不能为空", "Job description cannot be empty"),
    ("简历已保存", "Resume saved"),
    ("分析结果已保存", "Analysis saved"),
    ("职位已保存", "Job saved"),
    ("求职信已保存", "Cover letter saved"),
    ("已复制到剪贴板", "Copied to clipboard"),
    ("🔒 当前会话已隔离", "🔒 Current Session Isolated"),
    ("精准匹配职位", "Smart Job Matching"),
    ("专业简历精修", "Professional Resume Polish"),
    ("定制求职申请", "Tailored Applications"),
    ("简历已保存到本地", "Resume saved locally"),
    ("分析结果已保存到本地", "Analysis saved locally"),
    ("职位已保存到本地", "Job saved locally"),
    ("求职信已保存到本地", "Cover letter saved locally"),
    ("建议您准备好以下任一备选方案", "Please prepare one of the following alternatives"),
    ("确保每个用户看到干净的环境", "Ensure every user sees a clean environment"),
    ("页面加载时初始化干净的会话", "Initialize a clean session when page loads"),
    ("防止访问不存在的元素导致崩溃", "Prevent crashes when accessing non-existent elements"),
    ("彻底清理文本中的问题字符", "Thoroughly clean problem characters from text"),
    ("取消后您仍可使用到到期日", "You can still use it until the expiry date after cancellation"),
    ("解析简历文本为结构化数据", "Parse resume text into structured data"),
    ("提取职位信息用于写求职信", "Extract job info for writing cover letter"),
    ("使用提取的职位信息生成求职信", "Use extracted job info to generate cover letter"),
    ("查找分析结果卡片后面插入", "Find and insert after analysis result card"),
    ("获取或创建当前会话的用户", "Get or create current session user"),
    ("存储提取的信息供后续使用", "Store extracted info for later use"),
    ("自动滚动到分析结果区域中心", "Auto-scroll to analysis result area center"),
    ("等待一小段时间确保渲染稳定", "Wait a moment to ensure rendering is stable"),
    ("记录和管理所有投递的职位申请", "Record and manage all submitted job applications"),
    ("这样可以更好地保护您的隐私安全。", "This helps protect your privacy better."),
    ("在求职信结果区域后插入质量检测结果", "Insert quality check result after cover letter area"),
    ("在求职信页面添加质量检测按钮", "Add quality check button to cover letter page"),
    ("根据申请成功率重新定义等级颜色", "Redefine level colors based on application success rate"),
    ("还根据当地职场文化调整表达方式", "Also adapt expressions based on local workplace culture"),
    ("自动填充当前职位信息到求职信", "Auto-fill current position info into cover letter"),
    ("您的简历和分析结果会自动保存", "Your resume and analysis results are automatically saved"),
    ("我们为您保存本次分析结果", "We saved this analysis result for you"),
    ("请手动确认或补充以下信息", "Please manually confirm or supplement the following information"),
    ("自动切换到求职信页面并填充", "Auto-switch to cover letter page and fill in"),
    ("然后粘贴到下面的输入框中", "Then paste into the input box below"),
    ("请先", "Please first"),
    ("上传或粘贴简历", "upload or paste your resume"),
    ("创建用户画像", "create a user profile"),
    ("告诉我", "Tell me"),
    ("可以直接从 Word 文档复制内容粘贴进来", "You can copy content directly from a Word document and paste here"),
    ("从 Word 文档复制粘贴", "Copy from Word document"),
    ("请在左侧输入框粘贴职位描述", "Paste job description in the left input"),
    ("从左侧粘贴", "Paste from left"),
    ("© 2026 JobMatchAI", "© 2026 JobMatchAI"),
    ("保留所有权利。", "All rights reserved."),
    ("告诉我", "Tell me"),
    ("告诉我们", "Tell us"),
    ("粘贴招聘平台的职位链接", "Paste job posting URL from any job board"),
    ("从招聘链接抓取职位信息", "Fetch job info from posting URL"),
    ("粘贴职位描述文本", "Paste Job Description Text"),
    ("上传文档", "Upload Document"),
    ("粘贴文本", "Paste Text"),
    ("职位链接", "Job URL"),
    ("上传职位描述文档", "Upload Job Description Document"),
    ("📋 当前职位信息", "📋 Current Position"),
    ("📁 已保存的职位", "📁 Saved Jobs"),
    ("暂无保存的职位，请先添加", "No saved jobs yet, add one above"),
    ("确认并使用此职位", "Confirm & Use This Position"),
    ("🔍 尝试抓取", "🔍 Try to Fetch"),
    ("确认", "Confirm"),
    ("语言", "Language"),
    ("告诉我", "Tell me"),
    ("我们会将您的简历内容与意向职位描述进行匹配", "We match your resume content with the job description"),
    ("生成高度定制化的求职申请", "generate highly tailored job applications"),
    ("省时省力", "saving time and effort"),
]

CSS = [
    ("/* 动画 */", "/* Animations */"),
    ("/* 3步流程 */", "/* 3-Step Process */"),
    ("/* 价值主张卡片 */", "/* Value Cards */"),
    ("/* 底部Register区域 */", "/* Footer Register Area */"),
    ("/* 底部注册区域 */", "/* Footer Register Area */"),
    ("/* 底部登陆区域 */", "/* Footer Login Area */"),
    ("/* 底部语种翻译区域 */", "/* Footer Translation Area */"),
    ("/* 注册弹窗样式 */", "/* Register Modal Styles */"),
    ("/* 登录弹窗样式 */", "/* Login Modal Styles */"),
    ("<!-- Hero Section - 产品亮点 -->", "<!-- Hero Section -->"),
    ("<!-- 3步流程 -->", "<!-- 3-Step Process -->"),
    ("<!-- 立即开始按钮 -->", "<!-- Get Started Button -->"),
    ("<!-- 价值主张卡片 -->", "<!-- Value Cards -->"),
    ("<!-- 功能标签页 -->", "<!-- Feature Tabs -->"),
    ("<!-- Target Position页面 -->", "<!-- Target Position Page -->"),
    ("<!-- 收集信息说明 -->", "<!-- Info Collection Note -->"),
    ("<!-- 简历精修页面 -->", "<!-- Resume Polish Page -->"),
    ("<!-- 求职信页面 -->", "<!-- Cover Letter Page -->"),
    ("<!-- 职位搜索页面 -->", "<!-- Job Search Page -->"),
    ("<!-- 职位搜索结果区域 -->", "<!-- Job Search Results -->"),
    ("<!-- 选项卡 - 简化为两个主要选项 -->", "<!-- Tabs - Simplified -->"),
    ("<!-- 链接输入 -->", "<!-- URL Input -->"),
    ("<!-- 文档上传 -->", "<!-- Document Upload -->"),
    ("<!-- 抓取/上传结果 -->", "<!-- Fetch/Upload Result -->"),
    ("<!-- Paste Text输入区 -->", "<!-- Paste Text Area -->"),
    ("<!-- Job Link卡片（求职信用） -->", "<!-- Job Link Card (for Cover Letter) -->"),
    ("<!-- 已Save职位列表 -->", "<!-- Saved Jobs List -->"),
    ("<!-- 简历+职位匹配提示 -->", "<!-- Resume + Job Match Notice -->"),
    ("<!-- 隐私保护提醒 - 关于敏感信息 -->", "<!-- Privacy Notice -->"),
    ("<!-- 简历上传成功提示 -->", "<!-- Resume Upload Success -->"),
    ("<!-- 隐私保护提醒 -->", "<!-- Privacy Notice -->"),
    ("<!-- 语种翻译功能 -->", "<!-- Translation Feature -->"),
    ("<!-- 简历翻译功能说明 -->", "<!-- Resume Translation Info -->"),
    ("<!-- 简历翻译区域 -->", "<!-- Resume Translation Area -->"),
    ("<!-- 隐私声明区域 -->", "<!-- Privacy Statement Area -->"),
    ("<!-- 分析结果区域 -->", "<!-- Analysis Result Area -->"),
    ("<!-- 求职信区域 -->", "<!-- Cover Letter Area -->"),
    ("<!-- 求职信结果区域 -->", "<!-- Cover Letter Result Area -->"),
    ("<!-- 求职信质量检测区域 -->", "<!-- Cover Letter Quality Check Area -->"),
    ("<!-- 求职信工具栏 -->", "<!-- Cover Letter Toolbar -->"),
    ("<!-- 求职信文本区 -->", "<!-- Cover Letter Text Area -->"),
    ("<!-- 调整语气选项 -->", "<!-- Tone Adjustment Options -->"),
    ("<!-- 模版列表 -->", "<!-- Template List -->"),
    ("<!-- Word简历预览 -->", "<!-- Word Resume Preview -->"),
    ("<!-- Word简历导出 -->", "<!-- Word Resume Export -->"),
    ("<!-- 简历模版 -->", "<!-- Resume Templates -->"),
    ("<!-- 会员权益说明 -->", "<!-- Membership Benefits -->"),
    ("<!-- 会员价格表 -->", "<!-- Pricing Table -->"),
    ("<!-- 会员订阅卡片 -->", "<!-- Subscription Cards -->"),
    ("<!-- 订阅成功弹窗 -->", "<!-- Success Popup -->"),
    ("<!-- 语种选择器 -->", "<!-- Language Selector -->"),
    ("<!-- 语种切换按钮 -->", "<!-- Language Toggle -->"),
    ("<!-- 分析结果弹窗 -->", "<!-- Analysis Result Modal -->"),
    ("<!-- 简历分析结果 -->", "<!-- Resume Analysis Results -->"),
    ("<!-- 简历预览 -->", "<!-- Resume Preview -->"),
    ("<!-- 求职信预览 -->", "<!-- Cover Letter Preview -->"),
    ("<!-- 简历上传区 -->", "<!-- Resume Upload Area -->"),
    ("<!-- 简历解析区 -->", "<!-- Resume Parse Area -->"),
    ("<!-- 简历预览区 -->", "<!-- Resume Preview Area -->"),
    ("<!-- 职位信息区 -->", "<!-- Job Info Area -->"),
    ("<!-- 职位详情区 -->", "<!-- Job Detail Area -->"),
    ("<!-- 职位匹配区 -->", "<!-- Job Match Area -->"),
    ("<!-- 职位搜索表单 -->", "<!-- Job Search Form -->"),
    ("<!-- 求职信质量检测 -->", "<!-- Cover Letter Quality Check -->"),
    ("<!-- 质量检测弹窗 -->", "<!-- Quality Check Popup -->"),
    ("<!-- 质量检测结果 -->", "<!-- Quality Check Result -->"),
    ("<!-- 加载动画区域 -->", "<!-- Loading Area -->"),
    ("<!-- 通知提示 -->", "<!-- Notifications -->"),
    ("<!-- Toast通知 -->", "<!-- Toast Notification -->"),
    ("<!-- 模态框遮罩 -->", "<!-- Modal Overlay -->"),
    ("<!-- 会员介绍 -->", "<!-- Membership Info -->"),
    ("<!-- 会员福利 -->", "<!-- Membership Benefits -->"),
    ("<!-- 价格卡片 -->", "<!-- Pricing Cards -->"),
    ("<!-- 订阅按钮 -->", "<!-- Subscribe Button -->"),
    ("<!-- 订阅成功 -->", "<!-- Subscription Success -->"),
    ("<!-- 订阅确认 -->", "<!-- Subscription Confirmation -->"),
    ("<!-- 取消订阅 -->", "<!-- Cancel Subscription -->"),
    ("<!-- 会员到期 -->", "<!-- Membership Expiry -->"),
    ("<!-- 积分区域 -->", "<!-- Points Area -->"),
    ("<!-- 通知区域 -->", "<!-- Notification Area -->"),
    ("<!-- 页脚区域 -->", "<!-- Footer Area -->"),
    ("<!-- 隐私区域 -->", "<!-- Privacy Area -->"),
    ("<!-- 链接区域 -->", "<!-- Links Area -->"),
]

input_path = '/Users/weili/WorkBuddy/Claw/JobMatchAI-Overseas/frontend/index-en.html'
output_path = '/Users/weili/WorkBuddy/Claw/JobMatchAI-Overseas/frontend/index-en-new.html'

with open(input_path, 'r', encoding='utf-8') as f:
    content = f.read()

original = content

content = content.replace('lang="zh-CN"', 'lang="en"')

for cn, en in BASIC:
    content = content.replace(cn, en)

for cn, en in CSS:
    content = content.replace(cn, en)

changes = sum(1 for cn, en in BASIC if cn in original)
print(f'Made {changes} basic replacements')

remaining_lines = sum(1 for line in content.split('\n') if re.search(r'[\u4e00-\u9fff]', line))
remaining_chars = len(re.findall(r'[\u4e00-\u9fff]', content))
print(f'Remaining {remaining_lines} lines with Chinese, {remaining_chars} Chinese chars')

with open(output_path, 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Saved to {output_path}')
