#!/usr/bin/env python3
"""Smart English translator for index-en-new.html - focused on UI strings."""

import re

with open('/Users/weili/WorkBuddy/Claw/JobMatchAI-Overseas/frontend/index-en-new.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Priority 1: Most common UI phrases (replace longer strings first)
priority1 = [
    ('简历上传成功', 'Resume uploaded successfully'),
    ('复制成功！请粘贴到简历中。', 'Copied! Please paste into your resume.'),
    ('处理中，请稍候', 'Processing, please wait'),
    ('网络错误', 'Network error'),
    ('生成失败', 'Generation failed'),
    ('请稍候', 'Please wait'),
    ('上传意向', 'Upload Target'),
    ('下一步推荐', 'Next Steps'),
    ('智能分析', 'Smart Analysis'),
    ('一键', 'One-click'),
    ('精修后的', 'Polished'),
    ('手动输入', 'Manual input'),
    ('无法抓取', 'Cannot fetch'),
    ('请填写', 'Please fill in'),
    ('已完成', 'Completed'),
    ('分析结果', 'Analysis Result'),
    ('工作经验', 'Work Experience'),
    ('描述文档', 'Description doc'),
    ('显示成功提示', 'Show success notification'),
    ('完成动画', 'Completion animation'),
    ('高优先级', 'High Priority'),
    ('操作按钮', 'Action buttons'),
    ('精修完成', 'Polish complete'),
    ('筛选中', 'Filtering'),
    ('面试中', 'Interviewing'),
    ('上传中', 'Uploading'),
    ('抓取中', 'Fetching'),
    ('搜索中', 'Searching'),
    ('匹配中', 'Matching'),
    ('请重试', 'Please try again'),
    ('请先', 'Please first'),
    ('精修', 'Polish'),
    ('意向', 'Target'),
    ('检测到', 'Detected'),
    ('文本文件', 'Text file'),
    ('记录', 'Record'),
    ('链接', 'Link'),
    ('证书', 'Certificate'),
    ('定制', 'Custom'),
    ('匹配', 'Match'),
    ('提示信息', 'Tips'),
    ('检测', 'Check'),
    ('预览', 'Preview'),
    ('重置', 'Reset'),
    ('列表', 'List'),
    ('设置', 'Settings'),
    ('内容', 'Content'),
    ('格式', 'Format'),
    ('页码', 'Page'),
    ('页数', 'Pages'),
    ('页', ''),
    ('请选择', 'Please select'),
    ('正在', 'Currently'),
    ('预计需要', 'Est. time'),
    ('当前', 'Current'),
    ('标签', 'Tag'),
    ('失败', 'Failed'),
    ('已下载', 'Downloaded'),
    ('粘贴', 'Paste'),
    ('下载', 'Download'),
    ('使用', 'Use'),
    ('复制', 'Copy'),
    ('文档', 'Document'),
    ('生成', 'Generate'),
    ('可选', 'Optional'),
    ('显示', 'Show'),
    ('备选', 'Alternative'),
    ('部分', 'Partial'),
    ('页面', 'Page'),
    ('名称', 'Name'),
    ('信息', 'Info'),
    ('描述', 'Description'),
    ('待填写', 'Required'),
    ('已', 'Done'),
    ('清理', 'Clear'),
    ('条修改', ' changes'),
    ('已接受', 'Accepted'),
    ('结构', 'Structure'),
    ('简历', 'Resume'),
    ('求职信', 'Cover Letter'),
    ('职位', 'Job'),
    ('求职', 'Job Search'),
    ('申请', 'Apply'),
    ('申请追踪', 'Application Tracker'),
    ('简历精修', 'Resume Polish'),
    ('简历分析', 'Resume Analysis'),
    ('简历翻译', 'Resume Translation'),
    ('职位搜索', 'Job Search'),
    ('职位详情', 'Job Details'),
    ('职位描述', 'Job Description'),
    ('职位匹配', 'Job Match'),
    ('职位抓取', 'Job Fetch'),
    ('职位链接', 'Job Link'),
    ('注册', 'Register'),
    ('登录', 'Sign In'),
    ('退出', 'Sign Out'),
    ('会员', 'Premium'),
    ('订阅', 'Subscribe'),
    ('关于我们', 'About Us'),
    ('隐私政策', 'Privacy Policy'),
    ('服务条款', 'Terms of Service'),
    ('保存', 'Save'),
    ('删除', 'Delete'),
    ('编辑', 'Edit'),
    ('查看', 'View'),
    ('管理', 'Manage'),
    ('刷新', 'Refresh'),
    ('提交', 'Submit'),
    ('发送', 'Send'),
    ('接收', 'Receive'),
    ('导入', 'Import'),
    ('导出', 'Export'),
    ('取消', 'Cancel'),
    ('确认', 'Confirm'),
    ('关闭', 'Close'),
    ('开始', 'Start'),
    ('继续', 'Continue'),
    ('跳过', 'Skip'),
    ('展开', 'Expand'),
    ('收起', 'Collapse'),
    ('升级', 'Upgrade'),
    ('降级', 'Downgrade'),
    ('续费', 'Renew'),
    ('启用', 'Enable'),
    ('禁用', 'Disable'),
    ('测试', 'Test'),
    ('调试', 'Debug'),
    ('修复', 'Fix'),
    ('优化', 'Optimize'),
    ('搜索', 'Search'),
    ('筛选', 'Filter'),
    ('排序', 'Sort'),
    ('同步', 'Sync'),
    ('备份', 'Backup'),
    ('恢复', 'Restore'),
    ('发布', 'Publish'),
    ('推送', 'Push'),
    ('拉取', 'Pull'),
    ('合并', 'Merge'),
    ('版本', 'Version'),
    ('类型', 'Type'),
    ('状态', 'Status'),
    ('时间', 'Time'),
    ('日期', 'Date'),
    ('数量', 'Qty'),
    ('错误', 'Error'),
    ('警告', 'Warning'),
    ('成功', 'Success'),
    ('提示', 'Tip'),
    ('提醒', 'Reminder'),
    ('历史', 'History'),
    ('最近', 'Recent'),
    ('推荐', 'Recommended'),
    ('热门', 'Popular'),
    ('最新', 'Latest'),
    ('趋势', 'Trend'),
    ('排名', 'Ranking'),
    ('积分', 'Points'),
    ('等级', 'Level'),
    ('经验', 'Experience'),
    ('技能', 'Skills'),
    ('认证', 'Certification'),
    ('作品集', 'Portfolio'),
    ('项目', 'Project'),
    ('案例', 'Case'),
    ('文章', 'Article'),
    ('博客', 'Blog'),
    ('评论', 'Comment'),
    ('回复', 'Reply'),
    ('点赞', 'Like'),
    ('收藏', 'Favorite'),
    ('分享', 'Share'),
    ('转发', 'Repost'),
    ('关注', 'Follow'),
    ('粉丝', 'Followers'),
    ('好友', 'Friends'),
    ('群组', 'Group'),
    ('社区', 'Community'),
    ('公告', 'Announcement'),
    ('通知', 'Notification'),
    ('日程', 'Schedule'),
    ('日历', 'Calendar'),
    ('待办', 'Todo'),
    ('任务', 'Task'),
    ('目标', 'Goal'),
    ('计划', 'Plan'),
    ('网络', 'Network'),
    ('系统', 'System'),
    ('应用', 'App'),
    ('用户', 'User'),
    ('管理员', 'Admin'),
    ('客服', 'Support'),
    ('帮助', 'Help'),
    ('关于', 'About'),
    ('联系', 'Contact'),
    ('邮箱', 'Email'),
    ('电话', 'Phone'),
    ('地址', 'Address'),
    ('公司', 'Company'),
    ('公司名称', 'Company Name'),
    ('姓名', 'Name'),
    ('城市', 'City'),
    ('国家', 'Country'),
    ('语言', 'Language'),
    ('语言能力', 'Languages'),
    ('工作年限', 'Years of Experience'),
    ('薪资范围', 'Salary Range'),
    ('工作类型', 'Job Type'),
    ('学历', 'Education'),
    ('学位', 'Degree'),
    ('学校', 'School'),
    ('专业', 'Major'),
    ('综合评分', 'Overall Score'),
    ('匹配度', 'Match Score'),
    ('质量评分', 'Quality Score'),
    ('加载中', 'Loading'),
    ('初始化中', 'Initializing'),
    ('解析中', 'Parsing'),
    ('导出中', 'Exporting'),
    ('复制中', 'Copying'),
    ('简历已保存', 'Resume saved'),
    ('分析结果已保存', 'Analysis saved'),
    ('已复制到剪贴板', 'Copied to clipboard'),
    ('暂无分析结果', 'No analysis results yet'),
    ('请先上传或粘贴简历并点击分析', 'Please upload or paste your resume and click Analyze'),
    ('正在分析简历，请稍候', 'Analyzing resume, please wait...'),
    ('简历分析完成', 'Resume analysis complete'),
    ('职位要求', 'Requirements'),
    ('任职要求', 'Requirements'),
    ('岗位要求', 'Requirements'),
    ('岗位职责', 'Responsibilities'),
    ('主要职责', 'Main Responsibilities'),
    ('优先条件', 'Preferred Qualifications'),
    ('加分项', 'Nice to Have'),
    ('薪资待遇', 'Compensation'),
    ('工作地点', 'Location'),
    ('工作经验', 'Work Experience'),
    ('学历要求', 'Education Required'),
    ('招聘人数', 'Number of Hires'),
    ('发布时间', 'Posted Date'),
    ('公司规模', 'Company Size'),
    ('公司行业', 'Industry'),
    ('公司官网', 'Website'),
    ('立即申请', 'Apply Now'),
    ('收藏职位', 'Save Job'),
    ('取消收藏', 'Unsave'),
    ('已收藏', 'Saved'),
    ('推荐职位', 'Recommended Jobs'),
    ('相似职位', 'Similar Jobs'),
    ('搜索结果', 'Search Results'),
    ('共', 'Total'),
    ('条结果', 'results'),
    ('第', 'Page'),
    ('上一页', 'Prev'),
    ('下一页', 'Next'),
    ('返回顶部', 'Back to Top'),
    ('刷新页面', 'Refresh Page'),
    ('常见问题', 'FAQ'),
    ('用户指南', 'User Guide'),
    ('新手指南', 'Getting Started'),
    ('中文', 'Chinese'),
    ('英文', 'English'),
    ('丹麦文', 'Danish'),
    ('德文', 'German'),
    ('瑞典文', 'Swedish'),
    ('挪威文', 'Norwegian'),
    ('语种切换', 'Language Toggle'),
    ('语种选择', 'Language Selection'),
    ('请选择源语言', 'Select Source Language'),
    ('请选择目标语言', 'Select Target Language'),
    ('简历内容不能为空', 'Resume content cannot be empty'),
    ('职位描述不能为空', 'Job description cannot be empty'),
    ('请先上传或粘贴简历', 'Please upload or paste your resume first'),
    ('请先分析简历', 'Please analyze your resume first'),
    ('请先填写职位名称', 'Please enter the job title'),
    ('请先选择职位', 'Please select a position first'),
    ('请先填写求职信信息', 'Please fill in cover letter info'),
    ('简历已保存到本地', 'Resume saved locally'),
    ('分析结果已保存到本地', 'Analysis saved locally'),
    ('求职信生成完成', 'Cover letter generated'),
    ('简历翻译完成', 'Resume translated'),
    ('职位搜索完成', 'Job search complete'),
    ('已投递', 'Applied'),
    ('已回复', 'Replied'),
    ('已面试', 'Interviewed'),
    ('已拒绝', 'Rejected'),
    ('已录用', 'Offer'),
    ('待处理', 'Pending'),
    ('年度', 'Annual'),
    ('月度', 'Monthly'),
    ('季度', 'Quarterly'),
    ('价格', 'Price'),
    ('优惠', 'Discount'),
    ('立即', 'Now'),
    ('免费', 'Free'),
    ('付费', 'Paid'),
    ('发送验证码', 'Send Code'),
    ('重新发送', 'Resend'),
    ('验证码', 'Code'),
    ('账号已存在', 'Account exists'),
    ('账号不存在', 'Account not found'),
    ('密码错误', 'Wrong password'),
    ('登录成功', 'Sign in successful'),
    ('注册成功', 'Registration successful'),
    ('订阅成功', 'Subscribed'),
    ('订阅状态', 'Subscription Status'),
    ('订阅有效期', 'Subscription Valid Until'),
    ('功能权限', 'Feature Access'),
    ('简历精修次数', 'Resume Polish Count'),
    ('求职信生成次数', 'Cover Letter Count'),
    ('今日剩余', 'Remaining Today'),
    ('查看详情', 'View Details'),
    ('立即订阅', 'Subscribe Now'),
    ('关于我们', 'About Us'),
    ('加入我们', 'Join Us'),
    ('帮助中心', 'Help Center'),
    ('使用教程', 'Tutorial'),
    ('联系我们', 'Contact Us'),
    ('意见反馈', 'Feedback'),
    ('更新日志', 'Changelog'),
    ('免责声明', 'Disclaimer'),
    ('版权声明', 'Copyright'),
    ('隐私声明', 'Privacy Statement'),
    ('用户协议', 'User Agreement'),
    ('Cookie政策', 'Cookie Policy'),
    ('安全声明', 'Security Notice'),
    ('版本信息', 'Version Info'),
    ('当前版本', 'Current Version'),
    ('最新版本', 'Latest Version'),
    ('检查更新', 'Check Update'),
    ('深色模式', 'Dark Mode'),
    ('浅色模式', 'Light Mode'),
    ('跟随系统', 'Follow System'),
    ('语言设置', 'Language'),
    ('切换语言', 'Switch Language'),
    ('语种', 'Language'),
    ('源语言', 'Source'),
    ('目标语言', 'Target'),
    ('翻译', 'Translate'),
    ('翻译中', 'Translating'),
    ('工作经历', 'Work Experience'),
    ('教育背景', 'Education'),
    ('技能特长', 'Skills'),
    ('语言能力', 'Languages'),
    ('项目经验', 'Projects'),
    ('培训经历', 'Training'),
    ('证书资质', 'Certifications'),
    ('未完成', 'Incomplete'),
    ('处理中', 'Processing'),
    ('等待中', 'Waiting'),
    ('生成中', 'Generating'),
    ('精修中', 'Polishing'),
    ('分析中', 'Analyzing'),
    ('保存中', 'Saving'),
    ('匹配中', 'Matching'),
    ('检测中', 'Checking'),
    ('重置', 'Reset'),
    ('中', ''),
    ('的', ''),
    ('或', '/'),
    ('在', 'in'),
    ('到', 'to'),
    ('例如', 'e.g.'),
    ('能', 'Can'),
    ('可', ''),
    ('年', 'yr'),
    ('秒', 'sec'),
    ('上', ''),
    ('下', ''),
]

# Sort by length descending to avoid partial replacements
priority1.sort(key=lambda x: len(x[0]), reverse=True)

count = 0
for cn, en in priority1:
    if cn in content:
        count += content.count(cn)
        content = content.replace(cn, en)

print(f'Made {count} replacements')

# Check remaining
remaining_lines = sum(1 for line in content.split('\n') if re.search(r'[\u4e00-\u9fff]', line))
remaining_chars = len(re.findall(r'[\u4e00-\u9fff]', content))
print(f'Remaining: {remaining_lines} lines, {remaining_chars} Chinese chars')

with open('/Users/weili/WorkBuddy/Claw/JobMatchAI-Overseas/frontend/index-en-final.html', 'w', encoding='utf-8') as f:
    f.write(content)
print('Saved to index-en-final.html')
