#!/usr/bin/env python3
"""Final translation pass - cover remaining UI strings."""

import re

with open('/Users/weili/WorkBuddy/Claw/JobMatchAI-Overseas/frontend/index-en-final.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Remaining important UI strings
pass2 = [
    ('暂无分析结果', 'No analysis results yet'),
    ('请先上传或粘贴简历并点击分析', 'Please upload or paste your resume and click Analyze'),
    ('正在分析简历，请稍候', 'Analyzing resume, please wait...'),
    ('简历分析完成', 'Resume analysis complete'),
    ('暂无职位搜索结果', 'No job search results yet'),
    ('建议您准备好以下任一备选方案', 'Please prepare one of the following alternatives'),
    ('确保每个用户看到干净的环境', 'Ensure every user sees a clean environment'),
    ('页面加载时初始化干净的会话', 'Initialize a clean session when page loads'),
    ('防止访问不存在的元素导致崩溃', 'Prevent crashes when accessing non-existent elements'),
    ('彻底清理文本中的问题字符', 'Thoroughly clean problem characters from text'),
    ('取消后您仍可使用到到期日', 'You can still use it until the expiry date'),
    ('简历已保存到本地', 'Resume saved locally'),
    ('分析结果已保存到本地', 'Analysis saved locally'),
    ('请先填写职位名称或粘贴职位描述', 'Please enter a job title or paste a job description'),
    ('正在解析简历内容', 'Parsing resume content...'),
    ('简历内容为空，请先上传或粘贴简历', 'Resume content is empty. Please upload or paste a resume first.'),
    ('正在智能分析简历与职位的匹配度', 'Analyzing resume and job match...'),
    ('正在优化简历表达', 'Optimizing resume expressions...'),
    ('简历分析出错', 'Resume analysis error'),
    ('简历精修出错', 'Resume polish error'),
    ('求职信生成出错', 'Cover letter generation error'),
    ('请先填写求职信信息', 'Please fill in cover letter info'),
    ('请先选择职位', 'Please select a position first'),
    ('正在生成求职信', 'Generating cover letter...'),
    ('简历已保存', 'Resume saved'),
    ('分析结果已保存', 'Analysis saved'),
    ('职位已保存', 'Job saved'),
    ('求职信已保存', 'Cover letter saved'),
    ('请先上传简历', 'Please upload a resume first'),
    ('请先分析简历', 'Please analyze your resume first'),
    ('请手动确认或补充以下信息', 'Please manually confirm or supplement the following information'),
    ('自动切换到求职信页面并填充', 'Auto-switch to cover letter page and fill in'),
    ('然后粘贴到下面的输入框中', 'Then paste into the input box below'),
    ('正在滚动到分析结果区域', 'Scrolling to analysis results...'),
    ('直接', 'Direct'),
    ('为文本', 'As text'),
    ('暂无职位搜索结果', 'No job search results'),
    ('暂无职位详情', 'No job details'),
    ('正在抓取职位信息', 'Fetching job info...'),
    ('抓取失败', 'Fetch failed'),
    ('建议您提供更完整的职位描述', 'Please provide a more complete job description'),
    ('工作职责与要求', 'Responsibilities & Requirements'),
    ('精准匹配职位', 'Smart Job Matching'),
    ('专业简历精修', 'Professional Resume Polish'),
    ('定制求职申请', 'Tailored Applications'),
    ('🔒 当前会话已隔离', '🔒 Current Session Isolated'),
    ('解析简历文本为结构化数据', 'Parse resume text into structured data'),
    ('提取职位信息用于写求职信', 'Extract job info for writing cover letter'),
    ('使用提取的职位信息生成求职信', 'Use extracted job info to generate cover letter'),
    ('查找分析结果卡片后面插入', 'Find and insert after analysis result card'),
    ('获取或创建当前会话的用户', 'Get or create current session user'),
    ('存储提取的信息供后续使用', 'Store extracted info for later use'),
    ('自动滚动到分析结果区域中心', 'Auto-scroll to analysis result area center'),
    ('等待一小段时间确保渲染稳定', 'Wait a moment to ensure rendering is stable'),
    ('记录和管理所有投递的职位申请', 'Record and manage all submitted job applications'),
    ('这样可以更好地保护您的隐私安全', 'This helps protect your privacy better'),
    ('在求职信结果区域后插入质量检测结果', 'Insert quality check result after cover letter area'),
    ('在求职信页面添加质量检测按钮', 'Add quality check button to cover letter page'),
    ('根据申请成功率重新定义等级颜色', 'Redefine level colors based on application success rate'),
    ('还根据当地职场文化调整表达方式', 'Also adapt expressions based on local workplace culture'),
    ('自动填充当前职位信息到求职信', 'Auto-fill current position info into cover letter'),
    ('改进建议', 'Improvement suggestions'),
    ('下一步建议', 'Next steps'),
    ('去试试', 'Try it'),
    ('方案', 'Solution'),
    ('一步引导', 'Guided steps'),
    ('全部', 'All'),
    ('版本', 'Version'),
    ('为文本', 'As text'),
    ('区', 'Area'),
    ('区域', 'Area'),
    ('界面', 'Interface'),
    ('滚动', 'Scroll'),
    ('抓取', 'Fetch'),
    ('抓取卡片', 'Fetch card'),
    ('提取', 'Extract'),
    ('转换', 'Convert'),
    ('渲染', 'Render'),
    ('更新', 'Update'),
    ('解析', 'Parse'),
    ('处理', 'Process'),
    ('输出', 'Output'),
    ('添加', 'Add'),
    ('重新', 'Re-'),
    ('动态', 'Dynamic'),
    ('实时', 'Real-time'),
    ('自动', 'Auto'),
    ('文件', 'File'),
    ('调用', 'Call'),
    ('找', 'Find'),
    ('打开', 'Open'),
    ('与', 'and'),
    ('并', 'and'),
    ('从', 'from'),
    ('您', 'you'),
    ('此', 'this'),
    ('时', 'time'),
    ('年', 'yr'),
    ('等', 'etc.'),
    ('能', 'can'),
    ('不', 'not'),
    ('在', 'in'),
    ('到', 'to'),
    ('上', 'up'),
    ('下', 'down'),
    ('加载', 'Loading'),
    ('优先级', 'Priority'),
    ('高度', 'Height'),
    ('率', 'rate'),
    ('版', ''),
    ('传', 'Transmit'),
    ('功', 'Function'),
    ('是', 'is'),
    ('未', 'not'),
    ('未知', 'Unknown'),
    ('暂无', 'None'),
    ('请检查', 'Please check'),
    ('建议', 'Suggestion'),
    ('结果', 'Result'),
    ('选择', 'Select'),
    ('支持', 'Support'),
    ('本地', 'Local'),
    ('卡片', 'Card'),
    ('按钮', 'Button'),
    ('成为', 'Become'),
    ('直接', 'Direct'),
    ('按钮', 'Button'),
    ('告诉', 'Tell me'),
    ('我', 'me'),
    ('这', 'this'),
    ('个', ''),
    ('那', 'that'),
    ('来', 'come'),
    ('去', 'go'),
    ('请', 'please'),
    ('我', 'I'),
    ('你', 'you'),
    ('他', 'he'),
    ('她', 'she'),
    ('它', 'it'),
    ('我们', 'we'),
    ('他们', 'they'),
    ('自己', 'self'),
    ('的', ''),
    ('了', ''),
    ('着', ''),
    ('过', ''),
    ('得', ''),
    ('地', ''),
    ('吗', ''),
    ('吧', ''),
    ('呢', ''),
    ('啊', ''),
    ('哦', ''),
    ('嗯', ''),
    ('呀', ''),
    ('哪', ''),
    ('谁', ''),
    ('什么', 'what'),
    ('怎么', 'how'),
    ('为什么', 'why'),
    ('多少', 'how many'),
    ('很久', 'long'),
    ('一会儿', 'a while'),
    ('马上', 'soon'),
    ('已经', 'already'),
    ('正在', 'currently'),
    ('立刻', 'now'),
    ('然后', 'then'),
    ('接着', 'next'),
    ('再', 'again'),
    ('还', 'still'),
    ('很', 'very'),
    ('太', 'too'),
    ('最', 'most'),
    ('比较', 'relatively'),
    ('相当', 'quite'),
    ('更加', 'more'),
    ('稍微', 'slightly'),
    ('极其', 'extremely'),
    ('非常', 'very'),
    ('特别', 'especially'),
    ('尤其', 'particularly'),
    ('不过', 'however'),
    ('但是', 'but'),
    ('然而', 'however'),
    ('因此', 'therefore'),
    ('所以', 'so'),
    ('于是', 'thus'),
    ('既然', 'since'),
    ('因为', 'because'),
    ('如果', 'if'),
    ('虽然', 'although'),
    ('即使', 'even if'),
    ('只要', 'as long as'),
    ('除非', 'unless'),
    ('无论', 'no matter'),
    ('不管', 'regardless'),
    ('即使', 'even'),
    ('既...又...', 'both...and...'),
    ('一边...一边...', 'while...'),
    ('不但...而且...', 'not only...but also...'),
    ('若是', 'if'),
    ('倘若', 'if'),
    ('假如', 'if'),
    ('假使', 'if'),
    ('纵使', 'even if'),
    ('纵然', 'even'),
    ('尽管', 'despite'),
    ('无论', 'regardless'),
    ('哪怕', 'even'),
    ('就是', 'even'),
    ('只管', 'just'),
    ('尽管', 'despite'),
    ('任凭', 'regardless'),
    ('无', ''),
    ('有', ''),
    ('是', 'is'),
    ('在', 'at'),
    ('了', ''),
    ('和', 'and'),
    ('与', 'and'),
    ('及', 'and'),
    ('或', 'or'),
    ('但', 'but'),
    ('而', 'yet'),
    ('并', 'and'),
    ('即', 'i.e.'),
    ('则', 'then'),
    ('因', 'due to'),
    ('以', 'by'),
    ('为', 'for'),
    ('把', ''),
    ('被', 'by'),
    ('将', 'will'),
    ('于', 'at'),
    ('向', 'to'),
    ('对', 'for'),
    ('从', 'from'),
    ('自', 'from'),
    ('至', 'to'),
    ('到', 'to'),
    ('由', 'by'),
    ('在', 'at'),
    ('当', 'when'),
    ('每', 'each'),
    ('各', 'each'),
    ('某', 'some'),
    ('本', 'this'),
    ('该', 'the'),
    ('此', 'this'),
    ('其', 'its'),
    ('之', ''),
    ('所', 'place'),
    ('者', 'person'),
    ('这', 'this'),
    ('那', 'that'),
    ('这些', 'these'),
    ('那些', 'those'),
    ('某', 'a certain'),
    ('有的', 'some'),
    ('有些', 'some'),
    ('各个', 'each'),
    ('某个', 'a certain'),
    ('某些', 'some'),
    ('某事', 'something'),
    ('某人', 'someone'),
    ('某些', 'some'),
    ('何', 'what'),
    ('谁', 'who'),
    ('哪', 'which'),
    ('多少', 'how many'),
    ('几', 'several'),
    ('些', 'some'),
    ('吗', ''),
    ('呢', ''),
    ('吧', ''),
    ('呀', ''),
    ('啊', ''),
    ('哦', ''),
    ('唉', ''),
    ('呸', ''),
    ('咦', ''),
    ('嗯', ''),
    ('哈', ''),
    ('嘿', ''),
    ('喂', ''),
    ('嗨', ''),
    ('哎', ''),
    ('哟', ''),
    ('喔', ''),
    ('呃', ''),
    ('咳', ''),
    ('呸', ''),
]

pass2.sort(key=lambda x: len(x[0]), reverse=True)

count = 0
for cn, en in pass2:
    if cn in content:
        c = content.count(cn)
        count += c
        content = content.replace(cn, en)

print(f'Pass 2: made {count} replacements')

remaining_lines = sum(1 for line in content.split('\n') if re.search(r'[\u4e00-\u9fff]', line))
remaining_chars = len(re.findall(r'[\u4e00-\u9fff]', content))
print(f'Remaining: {remaining_lines} lines, {remaining_chars} Chinese chars')

with open('/Users/weili/WorkBuddy/Claw/JobMatchAI-Overseas/frontend/index-en-final.html', 'w', encoding='utf-8') as f:
    f.write(content)
print('Updated index-en-final.html')
